server:
  port: 8020
spring:
  application:
    name: iam
  profiles:
    include: druid
  security:
    oauth2:
      jwt:
        SigningKey: 0moe
  redis:
    host: ${SPRING_REDIS_HOST:122.51.158.110}
    database: 1
    password:  ${SPRING_REDIS_PASSWORD:LyzavGmsILOblYbN78DiWGzOhRPgaVtG}
    port: ${SPRING_REDIS_PORT:11954}
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: cn.lingmoe.iam.domain.entity
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: consul://${SPRING_CLOUD_CONSUL_HOST:consul.resource.0moe.cn}:${SPRING_CLOUD_CONSUL_PORT:80}?token=${SPRING_CLOUD_CONSUL_ACL_TOKEN:bef68e54-6195-2c65-227d-a840f9f745ee}
  protocol:
    port: 8102
    name: dubbo
  consumer:
    check: false
mybatis-plus:
  global-config:
    db-config:
      table-prefix: iam_
    banner: false